model_config:
  pretrained_model_name_or_path: "sp-embraceable/OLMo-2-1124-13B-Instruct-32k-Context-ChatML"
  device: "cuda"
  cache_dir: "/dss/dssmcmlfs01/pn39je/pn39je-dss-0001/go52tox/.cache"
  applied_module: 'attention'
  base_model_name: 'olmo2_13B_instruct'

training_config:
  learning_rate: 0.005
  lr_scheduler_type: 'cosine'
  warmup_steps: 50
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 20
  evaluation_strategy: 'epoch'
  save_strategy: 'epoch'
  load_best_model_at_end: True
  save_total_limit: 1
  report_to: "wandb"
  logging_strategy: "epoch"
  seed: 42
  do_train: True
  do_eval: True
  bf16: True
  output_dir: './output_olmo2'

data_config:
  train_size: 200
  task_name: "common_reason"
  data_path: "/dss/dssmcmlfs01/pn39je/pn39je-dss-0001/go52tox/lavine_prj/paper_prj/rep_pruning/dataset/data_with_instruct/commonsense/ARC-c"

jola_config:
  gate_lambda: 0.00004
  gate_scheduler: "expon"
